Use master
GO
CREATE DATABASE TH_Metadata
GO
USE TH_Metadata
DROP TABLE DATA_FLOW;
GO
CREATE TABLE DATA_FLOW
(
	ID INT NOT NULL IDENTITY(1,1),
	TABLE_NAME NVARCHAR(30) NULL,
	LSET DATETIME2 NULL,
	CET DATETIME2 NULL,
)


GO
TRUNCATE TABLE DATA_FLOW;

GO
INSERT INTO DATA_FLOW(TABLE_NAME,LSET,CET) VALUES ('STATE_AQI','01-01-2020 00:00', GETDATE());
INSERT INTO DATA_FLOW(TABLE_NAME,LSET,CET) VALUES ('US_COUNTIES', '01-01-2020 00:00',GETDATE());

SELECT * FROM DATA_FLOW


INSERT INTO DATA_FLOW(TABLE_NAME,LSET,CET) VALUES ('DefiningParaDim', '01-01-2020 00:00',GETDATE());
INSERT INTO DATA_FLOW(TABLE_NAME,LSET,CET) VALUES ('StateDimension ', '01-01-2020 00:00',GETDATE());
INSERT INTO DATA_FLOW(TABLE_NAME,LSET,CET) VALUES ('CountyDimension ', '01-01-2020 00:00',GETDATE());
INSERT INTO DATA_FLOW(TABLE_NAME,LSET,CET) VALUES ('AQICategoryDim', '01-01-2020 00:00',GETDATE());
INSERT INTO DATA_FLOW(TABLE_NAME,LSET,CET) VALUES ('AQIFactTable', '01-01-2020 00:00',GETDATE());
 